export const CALENDAR_CONSTANTS = {
	CALENDAR_NAME: "calendar",
	SOL_CALENDAR_NAME: "sol",
	EARTH_CALENDAR_NAME: "earth",
	YEAR_FORMAT: "YYYY",
	FULL_DATE_FORMAT: "YYYY-MM-DD",
	YEAR_MASK: "____",
	FULL_DATE_MASK: "____-__-__",
	YEAR_VIEW: "year",
	DAY_VIEW: "day",
	INVALID_DATE: "INVALID DATE",
};
